### ISSUE TITLE
Is there any option to remove server headers from response header?

### ISSUE THREAD

**Issue by RanaAshish** [apostrophecms/mechanic#47]
I have a requirement to remove the "server: nginx/version" header from the response header. Usually, people are doing it via nginx config by writing "server_tokens off" and other options. But I am not sure how to do the same with a mechanic. If I write it inside mechanic.conf I am afraid next time any mechanic command will override that.

**Comment by boutell** [comment]
Sure, check out "lazy overrides" in our documentation. https://www.npmjs.com/package/mechanic
